### PR TITLE
Tweak to allow the latest release of ramsey/uuid

### PR DESCRIPTION
**Pull request by mbadolato**
Updated composer.json to ```~3.0``` for ramsey/uuid and changed the namespace of the Uuid base class from Rhumsaa to Ramsey in ```Identity\UUID```

### CODE REVIEW

**Comment by nicolopignatelli** [comment]
PHP 5.3 is not supported by Ramsey\Uuid

**Comment by mbadolato** [comment]
@nicolopignatelli  Since so many other packages are starting to end support for 5.3 (and some 5.4) what do you think about moving up the minimum supported version? People still on 5.3 can still use the last supported version of this package.

**Comment by TomasVotruba** [comment]
@mbadolato :+1:

**Comment by mbadolato** [comment]
FYI, Seldek posted some [2015 stats](http://seld.be/notes/php-versions-stats-2015-edition) on PHP version usage according to composer/packagist this morning

**Comment by andrzejkupczyk** [comment]
:+1:

**Comment by mbadolato** [comment]
@nicolopignatelli For those of us that are using 3.0 of UUID already, a conflict is happening because this library cannot use that version, requiring a downgrade to 2.x.

**Comment by andrzejkupczyk** [comment]
@mbadolato You probably know about VCS? This is [my solution](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) for now.

**Comment by nicolopignatelli** [comment]
@mbadolato could you also change the min PHP version required?

**Comment by mbadolato** [comment]
@andrzejkupczyk Yes and that's what I'm doing locally but would prefer not to.

@nicolopignatelli Sure thing. Would you like it to be 5.5 or 5.6?

**Comment by localheinz** [comment]
@mbadolato 

:+1: for PHP5.4!

**Comment by mbadolato** [comment]
Made 5.4 the supported version (can change if @nicolopignatelli wants). Also removed 5.3 from travis. Commits squashed.

**Comment by lunetics** [comment]
+ should be merged. maybe geotools can be bumped to 0.6 version too?

**Comment by nicolopignatelli** [comment]
merged. I'll create a new major version since we dropped 5.3 support

**Pull request merged**
